### ISSUE TITLE
The Bones symlink seems to be causing issues with LSW on Windows 10 and Heroku Deployment

### ISSUE THREAD

**Issue by bushidocodes** [spmcbride1201/cookie-monsters#22]
Goal is to refactor the code to use relative links in place of the symlink.

**Comment by leafoflegend** [comment]
The symlinks are a lazy mans tool anyway. Wiping them should be all you need to do. (Plus any dependencies they installed for them). We can take a look together tomorrow.

**Comment by bushidocodes** [comment]
@leafoflegend Just wrapped up the refactor, and the tests are passing. I'm going to pull in some of the package.json start script stuff and then get this up.
