### ISSUE TITLE
Permission issue with start script

### ISSUE THREAD

**Issue by rachel-rocks-at-ruby** [spmcbride1201/cookie-monsters#44]
in bin startup file

**Comment by bushidocodes** [comment]
To add some more detail, the BASH script in `./bin/conditionalStart.sh` does not have the eXecute bit set when someone clones the repo for the first time. Despite the fact that we've change and merged the file in git commits, the permission metadata does not seem to be included. Another potential though is re-implementing this bash script using one of the BASH on JS runtimes to be able to run on native Windows.
